- name: Run Terraform Apply via HCP Terraform
  hosts: all
  gather_facts: false

  tasks:
    - name: Apply Terraform plan
      hashicorp.terraform.run:
        organization: "TechXchangeNL"
        workspace: "{{ workspace_name }}"
        token: "{{ terraform_token }}"
        run_apply: true
        poll: true
        interval: 5
        timeout: 1200
        tf_timeout: 6000
      register: tf_output

    - name: Show output
      debug:
        var: tf_output
